######################################################################
# Automatically generated by qmake (2.01a) ven. nov. 4 02:02:04 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Chemin.hxx Commun.dat Donnee.dat
SOURCES += Chemin.cxx
