all:
	cd consommateur && $(MAKE)
	cd producteur && $(MAKE)
clean:
	cd consommateur && $(MAKE) clean
	cd producteur && $(MAKE) clean

mrproper:
	cd consommateur && $(MAKE) mrproper
	cd producteur && $(MAKE) mrproper
