all:
	cd affichage && $(MAKE)
	cd client && $(MAKE)
	cd server && $(MAKE)
clean:
	cd affichage && $(MAKE) clean
	cd client && $(MAKE) clean
	cd server && $(MAKE) clean

mrproper:
	cd affichage && $(MAKE) mrproper
	cd client && $(MAKE) mrproper
	cd server && $(MAKE) mrproper
