all:
	cd common && $(MAKE)
	cd barriereentree && $(MAKE)
	cd bornepayement && $(MAKE)
	cd server && $(MAKE)
clean:
	cd common && $(MAKE) clean
	cd barriereentree && $(MAKE) clean
	cd bornepayement && $(MAKE) clean
	cd server && $(MAKE) clean
mrproper:
	cd common && $(MAKE) clean
	cd barriereentree && $(MAKE) mrproper
	cd bornepayement && $(MAKE) mrproper
	cd server && $(MAKE) mrproper
