######################################################################
# Automatically generated by qmake (2.01a) ven. nov. 18 17:25:36 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Ecran
INCLUDEPATH += . Ecran

# Input
HEADERS += FenetrePlanVille.h Ecran/fctTrace.h Commun.dat Donnee.dat
SOURCES += Chemin.cpp \
           Controle.cpp \
           FenetrePlanVille.cpp \
           Main.cpp \
           Ecran/fctTrace.cpp
